-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 21:29:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema d_gymdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d_gymdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `d_gymdb` DEFAULT CHARACTER SET utf8 ;
USE `d_gymdb` ;

-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_rol` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_rol` (
  `idtb_rol` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idtb_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_users` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_users` (
  `idtb_users` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `usuario` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tb_roll` INT NOT NULL,
  PRIMARY KEY (`idtb_users`),
  CONSTRAINT `fk_tb_users_tb_rol`
    FOREIGN KEY (`tb_roll`)
    REFERENCES `d_gymdb`.`tb_rol` (`idtb_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_users_tb_rol_idx` ON `d_gymdb`.`tb_users` (`tb_roll` ASC) ;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_departamentos` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_departamentos` (
  `id_departamentos` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_departamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_ciudades` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_ciudades` (
  `id_ciudades` INT NOT NULL,
  `descripcion` VARCHAR(60) NULL,
  `tb_departamentos_id_departamentos` INT NOT NULL,
  PRIMARY KEY (`id_ciudades`),
  CONSTRAINT `fk_tb_ciudades_tb_departamentos1`
    FOREIGN KEY (`tb_departamentos_id_departamentos`)
    REFERENCES `d_gymdb`.`tb_departamentos` (`id_departamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_ciudades_tb_departamentos1_idx` ON `d_gymdb`.`tb_ciudades` (`tb_departamentos_id_departamentos` ASC) ;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_photos` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_photos` (
  `id_photos` INT NOT NULL,
  `nombe` VARCHAR(100) NULL,
  `ruta_subida` VARCHAR(200) NOT NULL,
  `fecha_subida` DATETIME NULL,
  PRIMARY KEY (`id_photos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_clientes` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_clientes` (
  `id_clientes` INT NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `apellido` VARCHAR(30) NULL,
  `cedula` VARCHAR(12) NOT NULL,
  `ocupacion` VARCHAR(60) NULL,
  `edad` INT NULL,
  `altura` DECIMAL(10,2) NULL,
  `peso` DECIMAL(10,2) NULL,
  `email` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(50) NULL,
  `tb_ciudades` INT NOT NULL,
  `estado` VARCHAR(85) NULL,
  `tb_photos` INT NOT NULL,
  PRIMARY KEY (`id_clientes`),
  CONSTRAINT `fk_tb_clientes_tb_ciudades1`
    FOREIGN KEY (`tb_ciudades`)
    REFERENCES `d_gymdb`.`tb_ciudades` (`id_ciudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_clientes_tb_photos1`
    FOREIGN KEY (`tb_photos`)
    REFERENCES `d_gymdb`.`tb_photos` (`id_photos`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cedula_UNIQUE` ON `d_gymdb`.`tb_clientes` (`cedula` ASC) ;

CREATE INDEX `fk_tb_clientes_tb_ciudades1_idx` ON `d_gymdb`.`tb_clientes` (`tb_ciudades` ASC) ;

CREATE INDEX `fk_tb_clientes_tb_photos1_idx` ON `d_gymdb`.`tb_clientes` (`tb_photos` ASC) ;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_fichacliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_fichacliente` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_fichacliente` (
  `idfichacliente` INT NOT NULL,
  `tb_clientes` INT NOT NULL,
  `periodocontrol` VARCHAR(45) NULL,
  `fecha_lastcontrol` DATE NULL,
  `fecha_actual` DATE NULL,
  `pesoactual` DECIMAL(10,2) NULL,
  `avance` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idfichacliente`),
  CONSTRAINT `fk_tb_fichacliente_tb_clientes1`
    FOREIGN KEY (`tb_clientes`)
    REFERENCES `d_gymdb`.`tb_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_fichacliente_tb_clientes1_idx` ON `d_gymdb`.`tb_fichacliente` (`tb_clientes` ASC) ;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_rutina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_rutina` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_rutina` (
  `id_rutina` INT NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id_rutina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_plan` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_plan` (
  `idtb_plan` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `costo` DECIMAL(10,1) NULL,
  `cant_clases` VARCHAR(45) NULL,
  `tb_users` INT NOT NULL,
  PRIMARY KEY (`idtb_plan`),
  CONSTRAINT `fk_tb_plan_tb_users1`
    FOREIGN KEY (`tb_users`)
    REFERENCES `d_gymdb`.`tb_users` (`idtb_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_plan_tb_users1_idx` ON `d_gymdb`.`tb_plan` (`tb_users` ASC) ;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_pagos` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_pagos` (
  `id_pagos` INT NOT NULL,
  `nro_pago` INT NULL,
  `tb_clientes` INT NOT NULL,
  `tb_plan` INT NOT NULL,
  `montopagado` DECIMAL(10,2) NULL,
  `fecha_actual` DATE NULL,
  `validohasta` DATE NULL,
  PRIMARY KEY (`id_pagos`),
  CONSTRAINT `fk_tb_pagos_tb_clientes1`
    FOREIGN KEY (`tb_clientes`)
    REFERENCES `d_gymdb`.`tb_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pagos_tb_plan1`
    FOREIGN KEY (`tb_plan`)
    REFERENCES `d_gymdb`.`tb_plan` (`idtb_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_pagos_tb_clientes1_idx` ON `d_gymdb`.`tb_pagos` (`tb_clientes` ASC) ;

CREATE INDEX `fk_tb_pagos_tb_plan1_idx` ON `d_gymdb`.`tb_pagos` (`tb_plan` ASC) ;


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_entrenadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_entrenadores` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_entrenadores` (
  `id_entrenadores` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `formacion` VARCHAR(100) NULL,
  `direccion` VARCHAR(45) NULL,
  `ciudad` INT NOT NULL,
  `edad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_entrenadores`),
  CONSTRAINT `fk_tb_entrenadores_tb_ciudades1`
    FOREIGN KEY (`ciudad`)
    REFERENCES `d_gymdb`.`tb_ciudades` (`id_ciudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_entrenadores_tb_ciudades1_idx` ON `d_gymdb`.`tb_entrenadores` (`ciudad` ASC);


-- -----------------------------------------------------
-- Table `d_gymdb`.`tb_avance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `d_gymdb`.`tb_avance` ;

CREATE TABLE IF NOT EXISTS `d_gymdb`.`tb_avance` (
  `tb_clientes` INT NOT NULL,
  `tb_rutina` INT NOT NULL,
  `tb_entrenadores` INT NOT NULL,
  `fecha` DATE NULL,
  CONSTRAINT `fk_tb_avance_tb_clientes1`
    FOREIGN KEY (`tb_clientes`)
    REFERENCES `d_gymdb`.`tb_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_avance_tb_rutina1`
    FOREIGN KEY (`tb_rutina`)
    REFERENCES `d_gymdb`.`tb_rutina` (`id_rutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_avance_tb_entrenadores1`
    FOREIGN KEY (`tb_entrenadores`)
    REFERENCES `d_gymdb`.`tb_entrenadores` (`id_entrenadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_avance_tb_clientes1_idx` ON `d_gymdb`.`tb_avance` (`tb_clientes` ASC);

CREATE INDEX `fk_tb_avance_tb_rutina1_idx` ON `d_gymdb`.`tb_avance` (`tb_rutina` ASC);

CREATE INDEX `fk_tb_avance_tb_entrenadores1_idx` ON `d_gymdb`.`tb_avance` (`tb_entrenadores` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
